# Generated by Django 4.2.30 on 2026-05-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Gurux', 'verbose_name_plural': 'Guruxlar'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
    ]
